Hajar Emad

#### Q1: What's the version of Pandas that you installed?

In [1]:
import pandas as pd 

In [2]:
pd.__version__

'2.2.2'

---------------------------------------------------------------------------

####  Getting Data

In [3]:
df=pd.read_csv(' https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

Q2: Records count

How many records are in the dataset?

In [4]:
len(df)

9704

---------------------------------------------------------------

Q3: Fuel types

How many fuel types are presented in the dataset?

In [5]:
df['fuel_type'].unique() ,df['fuel_type'].nunique()

(array(['Gasoline', 'Diesel'], dtype=object), 2)

-----------------------------------------------------

Q4: Missing values

How many columns in the dataset have missing values?

In [6]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df.isnull().sum()[df.isnull().sum() > 0]


num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

In [8]:
sum(df.isnull().sum()>0)

4

----------------------------------------------------------------------

ََQ5: Max fuel efficiency
    
What's the maximum fuel efficiency of cars from Asia?

In [9]:
df['origin']=='Asia'

0       False
1       False
2       False
3       False
4       False
        ...  
9699    False
9700    False
9701    False
9702    False
9703     True
Name: origin, Length: 9704, dtype: bool

In [10]:
df[  df['origin']=='Asia'  ] ["fuel_efficiency_mpg"].max()

23.759122836520497

----------------------------------------------------------------------

Q6: Median value of horsepower

Find the median value of horsepower column in the dataset.

In [11]:
median_before = df.horsepower.median()
most_freq = df.horsepower.mode()[0]  #[0] ع لو في كذه حاجه مكرره يرجع واحد منها 
df['horsepower'] =df['horsepower'].fillna(most_freq)
median_after = df.horsepower.median()

print('horsepower median before: ', median_before , '\nmost freq value:' , most_freq ,'\nhorsepower medain after ' ,median_after)

horsepower median before:  149.0 
most freq value: 152.0 
horsepower medain after  152.0


----------------------------------------------------------------

Q7: Sum of weights

In [12]:
df_asia=df[ df['origin']=='Asia' ]  [['vehicle_weight','model_year']].head(7)
df_asia

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [13]:
X=df_asia.values #convert to array
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [14]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [15]:
import numpy as np 

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [16]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [17]:
w=XTX_inv.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [18]:
w.sum()

0.5187709081074007